export const ADD_STUDENT = 'ADD_STUDENT';
export const LOAD_COLUMNS_NAMES_FOR_STUDENTS_TABLE = 'LOAD_COLUMNS_NAMES_FOR_STUDENTS_TABLE';
export const CHANGE_STUDENTS_SUCCESS_FLAG = 'CHANGE_STUDENTS_SUCCESS_FLAG';
export const ADD_FILTERED_STUDENTS = 'ADD_FILTERED_STUDENTS';
export const CHANGE_FILTERED_SUCCESS_FLAG = 'CHANGE_FILTERED_SUCCESS_FLAG';

export const ADD_GROUP = 'ADD_GROUP';
export const LOAD_COLUMNS_NAMES_FOR_GROUP_TABLE = 'LOAD_COLUMNS_NAMES_FOR_GROUP_TABLE';
export const CHANGE_GROUP_SUCCESS_FLAG = 'CHANGE_GROUP_SUCCESS_FLAG';